### ISSUE TITLE
Cypress real events cause Cypress to throw the error "Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise"

### ISSUE THREAD

**Issue by iwt-ttaskov** [dmtrKovalenko/cypress-real-events#540]
Hi,
first, thank you for this wonderful package :)
Unfortunately, I get the following error (see below) from cypress when I use the real event methods.

I am using these versions in a typescript project:
```
"cypress": "12.17.4",
"cypress-real-events": "1.10.0",
```

The following code snippet causes Cypress to throw an error and can be used as a reference:
`cy.get('#innav-item-immobilienbewertung').realHover();`

This is the error from Cypress:

CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.

The command that returned the promise was:

  > `cy.realHover()`

The cy command you invoked inside the promise was:

  > `cy.doSyncCommand()`

Because Cypress commands are already promise-like, you don't need to wrap them or return your own promise.

Cypress will resolve your command with whatever the final Cypress command yields.

The reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.
    at <unknown> (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:143485:62)
    at tryCatcher (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromiseCtx (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:1613:10)
    at <unknown> (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:2382:20)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:3486:19)
    at Promise._then (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:1239:17)
    at Promise._passThrough (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:4110:17)
    at Promise.lastly.Promise.finally (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:4119:17)
    at Object.onRunnableRun (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:162210:53)
    at $Cypress.action (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:41015:28)
    at Runnable.run (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:144798:13)
    at next (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:154803:10)
    at <unknown> (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:154847:5)
    at timeslice (https://www.preview.immonet.de/__cypress/runner/cypress_runner.js:145082:27)
From Your Spec Code:
    at Homepage.navigateToRealEstateAppraisalPage (webpack:///../support/pages/homepage.ts:70:0)
    at Context.eval (webpack:///../e2e/realEstateAppraisal.spec.ts:30:0)

Thank you in advance for your reply :)

**Comment by iwt-ttaskov** [comment]
Issue solved. I will close the ticket.
