### ISSUE TITLE
"cy.realClick " is not a function

### ISSUE THREAD

**Issue by TiManGames** [dmtrKovalenko/cypress-real-events#711]
Hello, since last week we began recievning issues in our test runs regarding cypress real events on FireFox. We use realClick in some places, and our tests began failing on them.

This is most of the stack flow when failure occurs:

```
at __webpack_modules__</setRunnable/runnable.fn (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:138412:43)
at callFn (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:157028:21)
at __webpack_modules__</Runnable.prototype.run (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:157015:13)
at __webpack_modules__</create/onRunnableRun (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:162939:30)
at finallyHandler (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:4072:23)
at tryCatcher (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:1807:23)
at __webpack_modules__</module.exports/Promise.prototype._settlePromiseFromHandler (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:1519:31)
at __webpack_modules__</module.exports/Promise.prototype._settlePromise (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:1576:18)
at __webpack_modules__</module.exports/Promise.prototype._settlePromise0 (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:1621:10)
at __webpack_modules__</module.exports/Promise.prototype._settlePromises (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:1701:18)
at _drainQueueStep (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:2407:12)
at _drainQueue (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:2400:24)
at __webpack_modules__</Async.prototype._drainQueues (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:2416:16)
at __webpack_modules__</Async/this.drainQueues (https://st1.universe.cdp.gigya.com/__cypress/runner/cypress_runner.js:2286:14)
```

Env version:

Windows 11
Cypress Version:  13.15.0
Firefox browser Version: 128
Cypress Real Events: 1.13.0

**Comment by dmtrKovalenko** [comment]
Please read the readme, firefox is not supported.  You should not use real events in firefox
